print("==========================")
print("            LIST PRACTISE")
print("==========================")
print("Q1_Online food delivery system")
foods = ["Burger", "Pizza", "Fries", "Broast", "Sandwich"]
print("First food item:",foods[0])
print("Last food item:",foods[-1])
foods[2]="Pasta"
print("Replace fries to pasta:\n",foods)
foods.append("Zinger")
print("Zinger at the end:\n",foods)
foods.insert(2,"Shawarma")
print("Shawarama at index 2:\n",foods)
foods.remove("Pizza")
print("Remove pizza:\n",foods)
foods.pop(-1)
print("Remove last item:\n",foods)
print("Length of the list:",len(foods))
print("First three items:",foods[0:3])
print ("Last 2 items:",foods[-2:])
foods.reverse()
print("Reverse the list:\n", foods)
foods.sort()
print("Sorting of list:",foods)
print("==========================")

print("Q2_Student attendance management")
students = ["Ali", "Sara", "Ahmed", "Zoha Khan", "Hira"]
print("2 student:",students[1])
print("Last student:",students[-1])
students[2]="Hamza"
print(students)
students.append("Fatima")
print(students)
students.insert(2,"Ayesha")
print(students)
students.remove("Sara")
print(students)
students.pop(3)
print(students)
print("Length of the list:",len(students))
print(" 4 students:",students[1:5])
students.reverse()
print("final lists:",students)
print("==========================")

print("Q3_Mobile prize analysis")
prices = [45000, 120000, 30000, 85000, 60000]
prices.sort()
print(prices)
print("Higest prize:",prices[-1])
print("lowest price:",prices[0])
print("Ascending order:",prices)
prices.sort(reverse=True)
print("Descending order:",prices)
prices.append("50000")
print(prices)
prices.remove(85000)
print(prices)
prices.pop(4)
print(prices)
print(prices[:3])
print(prices[-2:])
print("Length of the list:",len(prices))
print("==========================")

print("Q4_Cricket team management")
players=["Babar", "Rizwan", "Shaheen", "Naseem", "Shadab"]
print("Captain name:",players[0])
print("Last player:",players[-1])
players[-1]="Imad"
print(players)
players.append("Umar")
print(players)
players.insert(1,"Asif")
print(players)
players.remove("Naseem")
print("First 4 players:" ,players[0:4])
print("Last 3 players:",players[-3:])
players.reverse()
print(players)
print("==========================")

print("Q5_Shopping cart system")
cart = ["Shoes", "Watch", "Bag", "Laptop", "Bottle"]
print("First item:",cart[0])
print("Last item:",cart[-1])
cart[4]="Headphones"
print(cart)
cart.append("keyboard")
print(cart)
cart.insert(1,"Mouse")
print(cart)
cart.remove("Bag")
print(cart)
cart.pop(-1)
print(cart)
print("Length of the list:",len(cart))
print(cart[1:4])
cart.reverse()
print(cart)
print("=========================")

print("Q6_Employ salary records")
salaries = [25000, 40000, 70000, 55000, 90000]
salaries.sort()
print(salaries)
print("Highest salary:",salaries [-1])
print("Lowest salary:",salaries[0])
print("Ascending order:",salaries)
salaries.sort(reverse =True)
print("Descending  order:",salaries)
salaries.append("60000")
print(salaries)
salaries.remove(55000)
print(salaries )
print ("Second higest salary:",salaries[1])
print("First 3 salaries:",salaries[0:2])
print("Length of the list:",len(salaries ))
print(salaries)
print("==========================")

print("Q7_Movie collection system")
movies = ["Avatar", "Inception", "Joker", "Titanic", "Interstellar"]
print("First movie name:",movies [0])
print("Last movie name:",movies[-1])
movies[2]="Batman"
print(movies)
movies.append("Luck")
print(movies)
movies.insert(3,"The Nun")
print(movies)
movies.remove("Titanic")
print(movies)
movies.pop(-1)
print(movies)
print("First 4 movies:",movies[:4])
movies.reverse()
print("Final list:",movies)
print("==========================")

print("Q8_Exam marks analysis")
marks = [78, 45, 90, 66, 82]
marks.sort
print("Higest marks:",marks[-1])
print("Lowest marks:",marks[0])
marks.sort
print("Sorting of marks:",marks )
marks.sort(reverse=True)
print("Descending order:",marks)
marks.append("58")
print(marks)
marks.remove(45)
print(marks)
print("Top 3 marks:",marks[0:3])
print("Last 2 marks:",marks[-2:])
print("Total subject:",len(marks))
print("Final list:",marks)
print("========================")

print("Q9_Website visitors record")
visitors = ["Ali", "Sara", "Ahmed", "Zoha Khan", "Hira"]
print("First visitor:",visitors[0])
print("Last visitor:",visitors[-2])
visitors.append("Umar")
print(visitors)
visitors.insert(2,"Uzma")
print(visitors)
visitors.remove("Ahmed")
print(visitors)
visitors.pop(-1)
print(visitors)
print("First 3 visitors:",visitors[0:3])
print("Last 3 visitors:",visitors[-3:])
visitors.reverse()
print(visitors)
print("Total visitors:",len(visitors))
print("==========================")

print("Q10_Programming languages system")
languages = ["Python", "JavaScript", "Java", "C++", "PHP"]
print("First language:",languages[0])
print("Last language:",languages[-1])
languages[-1]="TypeScript"
print(languages)
languages.append("Go")
print(languages)
languages.insert(2,"Rust")
print(languages)
languages.remove("Java")
print(languages)
print("First 4 languages:",languages[0:4])
print("Last 2 languages:",languages[-2:])
languages.sort()
print(languages)
languages.reverse()
print(languages)
print("Final list:",languages)
print("==========================")

